from typing import Tuple, List
import polars as pl
from curtrail.common.schema.ica_schema import metadata_reference_name, metadata_name


REFERENCE_ORG_COLUMN_NAME = "META_referenceOrg"
REFERENCE_TRIGGER_COLUMN_NAME = "META_referenceTrigger"
REFERENCE_PIPELINE_COLUMN_NAME = "META_referencePipeline"
REFERENCE_VERSION_COLUMN_NAME = "META_referenceVersion"
REFERENCE_REVISION_COLUMN_NAME = "META_referenceRevision"
REFERENCE_PORTAL_RUN_ID_COLUMN_NAME = "META_referencePortalRunId"

LINE_ITEM_COUNT_COLUMN_NAME = "line_item_count"


# can hand edit from here https://github.com/umccr/cwl-ica/releases
# to make the pipeline names neater
PIPELINE_ALIASES: dict[str, Tuple[str, str, str]] = {
    "812c4ee5-b0bd-4c55-b4c2-cafe70ecfc8e": (
        "dragen-wgts-dna-pipeline",
        "4-4-4",
        "20260104232900",
    ),
    "1f15f496-9f76-4bc5-98f7-e1e00ce8a407": (
        "dragen-wgts-rna-pipeline",
        "4-4-4",
        "20260104233012",
    ),
    "054ed1cc-4e29-46c0-afa0-8d2cf637a043": (
        "dragen-wgts-dna-pipeline",
        "4-4-6",
        "20260104232925",
    ),
    "d1d8ff20-e89f-4e6b-9aa2-557dbdd2a225": (
        "dragen-transcriptome-pipeline",
        "4-2-4",
        "20260108051253",
    ),
}


def tidy_ica_for_umccr(df: pl.DataFrame) -> pl.DataFrame:
    """
    Takes the original dataframe from curtrail and applies a series of transforms
    that are specific to UMCCR - but which are useful no matter what downstream
    analysis is being done.

    :param df: a DataFrame from curtrail
    :return:
    """
    # unnest the metadata struct, prefixing all its fields with META_
    df = df.with_columns(
        pl.col(metadata_name).struct.rename_fields(
            [f"META_{f}" for f in df[metadata_name].struct.fields]
        )
    ).unnest(metadata_name)

    # then decomposing the metadata reference column into constituent parts
    df = _decompose_reference(df)

    # then we want to unnest that reference struct and unify how
    # values are treated between pipeline and pipelineUuid
    _pipeline_name_map = {k: v[0] for k, v in PIPELINE_ALIASES.items()}
    _pipeline_version_map = {k: v[1] for k, v in PIPELINE_ALIASES.items()}

    df = (
        df.unnest("META_reference")
        .with_columns(
            pl.when(pl.col("META_pipelineUuid").is_not_null())
            .then(pl.col("META_pipelineUuid").replace(_pipeline_name_map))
            .otherwise(pl.col(REFERENCE_PIPELINE_COLUMN_NAME))
            .alias(REFERENCE_PIPELINE_COLUMN_NAME),
            pl.when(pl.col("META_pipelineUuid").is_not_null())
            .then(pl.col("META_pipelineUuid").replace(_pipeline_version_map))
            .otherwise(pl.col(REFERENCE_VERSION_COLUMN_NAME))
            .alias(REFERENCE_VERSION_COLUMN_NAME),
            # for dragen genome license runs we just say our org is umccr
            pl.when(pl.col("META_pipelineUuid").is_not_null())
            .then(pl.lit("umccr"))
            .otherwise(pl.col(REFERENCE_ORG_COLUMN_NAME))
            .alias(REFERENCE_ORG_COLUMN_NAME),
            # for dragen genome license runs we just say they are automated
            pl.when(pl.col("META_pipelineUuid").is_not_null())
            .then(pl.lit("automated"))
            .otherwise(pl.col(REFERENCE_TRIGGER_COLUMN_NAME))
            .alias(REFERENCE_TRIGGER_COLUMN_NAME),
        )
        .drop("META_pipelineUuid")
    )

    return df


def rollup_pipeline_line_items(df: pl.DataFrame) -> pl.DataFrame:
    """
    Joins together those compute line items that have been generated by the same
    pipeline run. This is mainly for those Dragen compute runs which have an
    addon costs based on the number of gigabases processed.

    We have some relatively arbitrary logic that combines fields from these
    line items into a single row value.

    :param df:
    :return:
    """
    return (
        df.group_by("META_id")
        .agg(
            pl.col("USAGE_CONTEXT").first(),
            # we choose the first billing date for the pipeline run, as it is the earliest
            pl.col("BILLING_DATE").min(),
            pl.col(REFERENCE_PIPELINE_COLUMN_NAME).drop_nulls().first(),
            pl.col(REFERENCE_VERSION_COLUMN_NAME).drop_nulls().first(),
            pl.col(REFERENCE_PORTAL_RUN_ID_COLUMN_NAME).drop_nulls().first(),
            pl.col("META_status").first(),
            # obviously sum the cost
            pl.col("COST").sum(),
            # a count so if we want we can tell those items that involve multi line items
            pl.len().alias(LINE_ITEM_COUNT_COLUMN_NAME),
            pl.concat_str(
                [pl.col("QUANTITY").cast(pl.String), pl.col("USAGE_UNIT")],
                separator=" ",
            )
            .str.join(" + ")
            .alias("run_data"),
        )
    )




def _decompose_reference(df: pl.DataFrame) -> pl.DataFrame:

    # some examples (trailing -<uuid> is stripped before parsing)
    # |reference:uog--manual--bclconvert-interop-qc--1-5-0--1-31--202603054112fcab|  (6 parts)
    # |reference:uog--automated--arriba-wgts-rna--2-5-0--20260228d4f9c3c7|           (5 parts)
    # |reference:Tsqn-STRL260316-v2ct260318_23Mar26_082017_e5294b|                   (1 part)

    _UUID_RE = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    _UUID_CAPTURE_RE = r"-(" + _UUID_RE + r")$"
    _UUID_SUFFIX_RE  = r"-"  + _UUID_RE + r"$"

    ref_col = "META_" + metadata_reference_name

    # ICA appends -<uuid> to every reference; validate it matches the row id then strip it
    mismatched = df.filter(
        pl.col(ref_col).str.extract(_UUID_CAPTURE_RE, 1) != pl.col("META_id")
    )
    if len(mismatched) > 0:
        raise ValueError(
            f"Reference '-<UUID>' suffix does not match id column in {len(mismatched)} rows"
        )

    df = df.with_columns(
        pl.col(ref_col).str.replace(_UUID_SUFFIX_RE, "").alias(ref_col)
    )

    # split into up to 6 fields.
    # 6-part rows: [org, trigger, pipeline, version, revision, portalRunId]
    # 5-part rows: [org, trigger, pipeline, version, portalRunId, null]
    df = df.with_columns(
        pl.col(ref_col).str.splitn("--", 6).struct.rename_fields([
            REFERENCE_ORG_COLUMN_NAME,
            REFERENCE_TRIGGER_COLUMN_NAME,
            REFERENCE_PIPELINE_COLUMN_NAME,
            REFERENCE_VERSION_COLUMN_NAME,
            REFERENCE_REVISION_COLUMN_NAME,
            REFERENCE_PORTAL_RUN_ID_COLUMN_NAME,
        ]).alias(ref_col)
    )

    # reconstruct the struct in one pass
    # For 5-part rows the portal run ID landed in META_referenceRevision
    # and META_referencePortalRunId is null; coalesce corrects both.
    _s = pl.col(ref_col)
    _portal_run_id = pl.coalesce(
        _s.struct.field(REFERENCE_PORTAL_RUN_ID_COLUMN_NAME),
        _s.struct.field(REFERENCE_REVISION_COLUMN_NAME),
    )

    return df.with_columns(
        pl.struct(
            _s.struct.field(REFERENCE_ORG_COLUMN_NAME),
            _s.struct.field(REFERENCE_TRIGGER_COLUMN_NAME),
            _s.struct.field(REFERENCE_PIPELINE_COLUMN_NAME),
            _s.struct.field(REFERENCE_VERSION_COLUMN_NAME),
            pl.when(_s.struct.field(REFERENCE_PORTAL_RUN_ID_COLUMN_NAME).is_null())
                .then(pl.lit(None).cast(pl.String))
                .otherwise(_s.struct.field(REFERENCE_REVISION_COLUMN_NAME))
                .alias(REFERENCE_REVISION_COLUMN_NAME),
            _portal_run_id.alias(REFERENCE_PORTAL_RUN_ID_COLUMN_NAME),
        ).alias(ref_col)
    )
